spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/resiido_db
spring.datasource.username=postgres
spring.datasource.password=resiidocs05

# This tells Hibernate to create the tables for you
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true