spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/resiido_db
spring.datasource.username=postgres
spring.datasource.password=resiidocs05
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.error.include-message=always
jwt.secret=${JWT_KEY}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=exampleresidence1@gmail.com
spring.mail.password=fcjd bkyd dkpe tjok
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=TRACE