POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "password123",
    "role": "RESIDENT"
}

### Create a Maintenance Request
POST http://localhost:8080/api/maintenance
Content-Type: application/json

{
    "title": "Broken Window",
    "description": "Cracked glass in living room",
    "status": "PENDING",
    "resident": {
        "id": 1
    }
}

### Manager updates the status to IN_PROGRESS
PUT http://localhost:8080/api/maintenance/1/status
Content-Type: text/plain

IN_PROGRESS

### Resident #1 hits the SOS Button
POST http://localhost:8080/api/sos/1

### See all ongoing SOS situations
GET http://localhost:8080/api/sos/active

### Manager creates a Rent bill
POST http://localhost:8080/api/payments
Content-Type: application/json

{
    "amount": 1100.00,
    "type": "RENT",
    "dueDate": "2024-06-01",
    "paid": false,
    "resident": {
        "id": 1
    }
}

### Get unpaid bills for Resident #1
GET http://localhost:8080/api/payments/resident/1/unpaid

### Mark bill as paid
PUT http://localhost:8080/api/payments/4/pay